In [ ]:
# Author: Arun Bamal
# Project: Data Engineering Assignmentimport sys
print(sys.executable)

c:\Users\arunb\Documents\data-engineering-assignment\venv\Scripts\python.exe

In [1]:
import duckdb

con = duckdb.connect()
print("DuckDB working!")

DuckDB working!

In [8]:
import duckdb

con = duckdb.connect()

df = con.execute("""
SELECT *
FROM read_csv_auto('C:/Users/arunb/Downloads/2019-Oct.csv')
LIMIT 10
""").fetchdf()

df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [9]:
con.execute("SELECT COUNT(*) FROM read_csv_auto('C:/Users/arunb/Downloads/2019-Oct.csv')").fetchall()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[(42448764,)]

In [10]:
con.execute("""
SELECT event_type, COUNT(*) as count
FROM read_csv_auto('C:/Users/arunb/Downloads/2019-Oct.csv')
GROUP BY event_type
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  event_type     count
0   purchase    742849
1       cart    926516
2       view  40779399

In [11]:
con.execute("""
SELECT brand, COUNT(*) as count
FROM read_csv_auto('C:/Users/arunb/Downloads/2019-Oct.csv')
WHERE brand IS NOT NULL
GROUP BY brand
ORDER BY count DESC
LIMIT 10
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     brand    count
0  samsung  5282775
1    apple  4122554
2   xiaomi  3083763
3   huawei  1111205
4  lucente   655861
5       lg   562404
6    bosch   557090
7     oppo   482887
8     sony   456644
9     acer   428153

In [12]:
con.execute("""
SELECT AVG(price)
FROM read_csv_auto('C:/Users/arunb/Downloads/2019-Oct.csv')
""").fetchall()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[(290.32366068503546,)]

In [7]:
import os

print(os.listdir())
print(os.listdir('data'))
print(os.listdir('data/raw'))

['01_schema_design.ipynb', '02_etl_pipeline.ipynb', '03_benchmarks.ipynb', '04_queries.ipynb', '05_visualizations.ipynb']

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [1]:
con.close()

NameError: name 'con' is not defined